# Fixed build configuration
---
include:
 - board: seeeduino_xiao_ble
   shield: tomkey_R
 - board: seeeduino_xiao_ble
   shield: tomkey_L dongle_display
   snippet: studio-rpc-usb-uart
 - board: seeeduino_xiao_ble
   shield: settings_reset
